### PR TITLE
(2307) Add Regulator column to decision data table for admin users

### PR DESCRIPTION
**Pull request by Gweaton**
# Changes in this PR

Adds "Regulator" column to the table on the decision data index page for Central Admin users.

#### Regulator user

image

#### Central admin user

image

### CODE REVIEW

**Review by richpjames — APPROVED** [review]
LGTM

**Review by bryangaledxw — COMMENTED** [review]
Did you take a look at the professions `ListEntryPresenter`? Where we're using ` 'overview'` and `'single-organisation'` as a key into a list of lists of fields. We're also using `type OrganisationsPresenterView = 'overview' | 'single-organisation'` in `OrganisationsPresenter`.

The code looks good, but my feeling is it's worth bring this more in line with those

**Comment by Gweaton** [comment]
> Did you take a look at the professions `ListEntryPresenter`? Where we're using ` 'overview'` and `'single-organisation'` as a key into a list of lists of fields. We're also using `type OrganisationsPresenterView = 'overview' | 'single-organisation'` in `OrganisationsPresenter`.
> 
> The code looks good, but my feeling is it's worth bring this more in line with those

Thanks for letting me know - turns out I hadn't looked in enough detail at those classes for this. I've updated the PR now and think it looks a lot better. Would you mind taking another look @bryangaledxw?

**Review by bryangaledxw — APPROVED** [review]
LGTM

**Pull request merged**
